version: 2.1

jobs:
  run_build:
    docker:
      - image: cimg/node:15.1
      - image: cimg/node:14.16
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run:
          name: Run Linter
          command: npm run lint
      - run:
          name: Run Production build
          command: npm run build

workflows:
  build_app:
    jobs:
      - run_build
